### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by akuckartz** [politik-bei-uns/frontend#2]
Wenn ich auf der Seite
https://beta.politik-bei-uns.de/document/5a4248d644875ce977c21d19
auf "öffnen" oder "download" klicke, dann sehe ich:

~~~
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key/><BucketName/><Resource>/politik-bei-uns/files/5a4248c844875ce977c1ef4d/5a4248d644875ce977c21d05</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
~~~

Ergänzung: anscheinend gibt es diese Meldung bei allen Dokumenten.

**Comment by the-infinity** [comment]
Gefixt. War ein Fehler, welcher durch den OParl Mirror Support entstanden ist. Siehe https://github.com/politik-bei-uns/frontend/commit/b4716fea5f94106d3e941b320957d63ea64c2396#diff-b2096f986d3a35f6a55b21bdf8177374
